from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.4.1")


##### setup report #####
configfile: "config/config.yaml"


report: "report/workflow.rst"

##### setup singularity #####

# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


##### load rules #####

include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/qc.smk"
include: "rules/remap_barcode.smk"
include: "rules/cellranger.smk"
#include: "rules/snaptools.smk"
#include: "rules/archr.smk"
#include: "rules/snapatac.smk"

##### target rules #####


rule all:
    input:
        get_final_output(),
