# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.tsv


ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 100
  # Genome build
  build: GRCh38
  # ucscname
  ucscname: hg38
  # cellranger transcriptome
  #reference_transcriptome: path/to/cellRangerReferences
  # bwa_index
  #bwa_index: path/to/bwa_index
  # chromosome size
  #chrom_size: path/to/chrom_size_file

params:
  # the parameters for trim_R2
  pattern: "(?P<UMI>.{10})(?P<BAR>.{7})(.{0,3})GGATTCGAGGAGCGTGTGCGAACTCAGACCA{i<=2,d<=2,e<=3}(?P<BAR>.{6})ATCCACGTGCTTGAGAGGCCAGAGCATTCG(((?P<TYPE>AG)(?P<BAR>.{3}))|((?P<TYPE>TC)(?P<BAR>.{3})))"
  # rna reads barcode
  rna_bar: TC
  # dna reads barcode
  dna_bar: AG
  # the illumina whitelist
  whitelist: config/3M-february-2018.txt.gz

# The tools in this pipeline use a broad range of resources and have been assigned to the following three categories.
# If there are not enough resources specified it can be adapted in the tools corresponding section.
computingResources:
  mem_mb:
    low: 2000
    medium: 16000
    high: 40000
  runtime:
    low: 60
    medium: 500
    high: 800
  threads:
    low: 1
    medium: 4
    high: 12

tools:
  # Cellranger Parameters.
  # It needs to be installed manually & the call in both cellranger rules needs to be adapted.
  # NOTE: please provide the full path to the cellranger installation
  # variousParams can be set as described in the Cellranger documentation
  cellranger_count:
    variousParams: "--chemistry auto --include-introns false"
    mkrefParams: "--ref-version=0.0.1"
    mkgtfParams: "--attribute=gene_biotype:protein_coding --attribute=gene_biotype:lncRNA --attribute=gene_biotype:antisense --attribute=gene_biotype:IG_LV_gene --attribute=gene_biotype:IG_V_gene --attribute=gene_biotype:IG_V_pseudogene --attribute=gene_biotype:IG_D_gene --attribute=gene_biotype:IG_J_gene --attribute=gene_biotype:IG_J_pseudogene --attribute=gene_biotype:IG_C_gene --attribute=gene_biotype:IG_C_pseudogene --attribute=gene_biotype:TR_V_gene --attribute=gene_biotype:TR_V_pseudogene --attribute=gene_biotype:TR_D_gene --attribute=gene_biotype:TR_J_gene --attribute=gene_biotype:TR_J_pseudogene --attribute=gene_biotype:TR_C_gene"
